### ISSUE TITLE
Consider moving all `cloud` commands to top level

### ISSUE THREAD

**Issue by hasheddan** [upbound/up#114]
### What problem are you facing?

Currently, `up` only has one top-level command (`up license`, which returns a link to Upbound's license information). All other commands fall under one of the following subcommands: `cloud`, `uxp`, `xpkg`. As Upbound's API operations (which currently fall under `up cloud ...` -- see full list below) no longer apply to only just the "cloud" hosted product, this subcommand makes less sense. Given that the only commands in `cloud` that do not fall under `controlplane` are `login` / `logout`, it could make sense to eliminate the `cloud` subcommand altogether and move all of its commands up a level.

### How could Upbound help solve your problem?

Moving some of the commands up a level was previously discussed in #65, though at that time there was concern around confusion with something like `up login` not being clear about where a user was actually logging in. As the Upbound product offerings have continued to mature, and the UXP and XPKG commands have been added under their own subcommands, this distinction has become less ambiguous. We can likely safely assume that a top-level command for the Upbound CLI is used to interact with the Upbound product. Furthermore, all other `up cloud` commands fall under the `controlplane` subcommand, clearly distinguishing where they are performing operations. Any confusion around this can be further eliminated by helpful clear help text and documentation.

### Current Cloud Commands

```
🤖 (up) up cloud -h
Usage: up cloud <command>

Interact with Upbound Cloud.

Flags:
  -h, --help                               Show context-sensitive help.
  -v, --version                            Print version and exit.

      --endpoint=https://api.upbound.io    Endpoint used for Upbound API ($UP_ENDPOINT).
      --profile=STRING                     Profile used to execute command ($UP_PROFILE).
  -a, --account=STRING                     Account used to execute command ($UP_ACCOUNT).

cloud
  cloud login
    Login to Upbound Cloud.

  cloud logout
    Logout from Upbound Cloud.

  cloud controlplane attach <name>
    Attach a self-hosted control plane.

  cloud controlplane create <name>
    Create a hosted control plane.

  cloud controlplane delete <id>
    Delete a control plane.

  cloud controlplane list
    List control planes for the account.

  cloud controlplane kubeconfig get --token=STRING <control-plane-ID>
    Get a kubeconfig for a control plane.

  cloud controlplane token create <control-plane-ID>
    Create a control plane token.

  cloud controlplane token delete <token-ID>
    Delete a control plane token.

  cloud controlplane token list <control-plane-ID>
    List tokens for the control plane.
```

**Comment by grantgumina** [comment]
I wanted to jot down a few thoughts ahead of our meeting tomorrow. It's important we have a clear vision for the experience, even if we won't be able to ship that entirely in Q3.

- With Upbound Enterprise shipping soon, we'll have products and features deploying in to primary states - multi-tenant and single tenant.

- Users should be able to login to the single tenant or the multitenant product using the `login` command.

- Keeping this in mind, I wonder if it's more intuitive for users to operate at an Organization level vs. product (cloud, enterprise, UXP, etc.) level.
    - For example, users could login to their account and perform operations on the organization (or personal account) they choose. Instead of `cloud controlplane token delete` it could be `controlplane token delete` as an example.

- Alternatively, we could keep the basic framework in place and replace `cloud` with `console`.

**Comment by grantgumina** [comment]
@hasheddan and I met this morning to discuss what we'll do here, and we came to the following decisions.

- Users will install Upbound Enterprise via `up enterprise install`. They'll supply their ID and token to authenticate with our licensing server.
- Users will be instructed to `up login` and supply the Upbound Enterprise endpoint for the optional organization parameter
- `cloud` subcommands will become top level commands
