### ISSUE TITLE
Fetch access key and create Secret on enterprise install

### ISSUE THREAD

**Issue by hasheddan** [upbound/up#115]
### What problem are you facing?

In order for Upbound's enterprise product to run, it must be provided with a signed access key for a customer's license. This should be incorporated into the installation flow, and the same credentials used to actually access the software artifacts should also be used to get the access key.

### How could Upbound help solve your problem?

Support fetching access key and creating `Secret` prior to downloading and installing enterprise software in the same `up enterprise install` command.

Epic #

**Comment by tnthornton** [comment]
@hasheddan what API endpoints does this flow hit on DMV? Is DMV currently setup to authenticate requests using the license credentials?

**Comment by tnthornton** [comment]
Second question is answered by https://github.com/upbound/dmv/issues/19
