### ISSUE TITLE
Show UXP version in `up ctp list` output

### ISSUE THREAD

**Issue by hasheddan** [upbound/up#126]
### What problem are you facing?

We currently display Name, ID, Hosted / Self-Hosted, and Status in the output for `up ctp list`. Another relevant attribute is what version of UXP the control plane is running.

### How could Upbound help solve your problem?

We should expose the UXP version in `up ctp list` output and / or consider offering a “wide” output version for informational commands to include additional information, such as k8s version.

Epic #

**Comment by RedbackThomson** [comment]
Closed as the introduction of spaces into cloud has fundamentally changed `up` and this is no longer applicable.
