### ISSUE TITLE
Prompt user for confirmation when performing destructive actions

### ISSUE THREAD

**Issue by hasheddan** [upbound/up#232]
### What problem are you facing?

When users are performing destructive actions, such as deleting a repository, control plane, or organization, we should prompt them for input to confirm they want to do so.

### How could Upbound help solve your problem?

Update all potentially destructive commands to prompt for confirmation.

**Comment by jastang** [comment]
Hey @hasheddan! If this isn't critically urgent, think I could give it a shot? Seems well-scoped enough that it's manageable and I'd love to contribute something small to our fave CLI. 🙂

**Comment by hasheddan** [comment]
@jastang absolutely! Top commands in my mind where we should add this include:
- `up repo delete`
- `up robot delete`
- `up robot token delete`
- `up org delete`

Other potential candidates include:
- `up upbound uninstall`
- `up uxp uninstall`

**Comment by jastang** [comment]
Exploring a bit, here's what I'm thinking:

- add `Force` flag to the delete commands (should it also be hidden?)
- use the internal `Prompter`, initializing and prompting on the appropriate hooks (`BeforeApply` and `AfterApply`)

Does that sound reasonable at a high level?

**Comment by hasheddan** [comment]
@jastang sounds right to me! I don't think `--force` needs to be hidden for this use case. It is currently hidden in the `up robot` commands due to the fact that users really _shouldn't_ be hitting the duplicates. Now that `--force` is performing a function (i.e. disabling the prompt) that we don't expect to be changed by future API updates, I think it makes sense for it to be visible :)
