### ISSUE TITLE
Duplicate robot accounts

### ISSUE THREAD

**Issue by plumbis** [upbound/up#254]
### What happened?
`up` allows for the creation of a robot account with the same name as an existing account. 

```shell
$ up robot create my-robot
upbound-docs/my-robot created

$ up robot list
NAME              ID                                     DESCRIPTION   CREATED
my-robot          4e551097-c4b1-4a18-bcab-5d68ab39865a                 18s
use-our-product   856f3a50-48af-4a22-84ca-da3cf10c2c06                 25d
my-robot          e1c30e71-b99f-4178-b1a2-9adf7232ac8a                 34h
```

The main problem with this is I can't delete either robot account since it only uses the name

```shell
$ up robot token create my-robot my-token --output=token.json
up: error: found multiple robots with name my-robot in upbound-docs
```

Epic #

### How can we reproduce it?

Create a robot account

`up robot create my-robot`

then do it again

`up robot create my-robot`

### What environment did it happen in?

```shell
$ up --version
v0.13.0
vagrant@kubecontroller-01
```

**Comment by hasheddan** [comment]
This is being addressed at the API level, rather than the CLI 👍🏻 Thanks for opening @plumbis!
