### ISSUE TITLE
Server URL in the Generated Kubeconfig for MCP is wrong

### ISSUE THREAD

**Issue by turkenh** [upbound/up#256]
### What happened?

The server URL in the Generated Kubeconfig for MCPs is wrong. 

URL path is set as `v1/controlPlanes/upbound/upbound:second-mcp/k8s` instead of `v1/controlPlanes/upbound/second-mcp/k8s`

### How can we reproduce it?

Try to connect to an MCP with `UP_MCP_EXPERIMENTAL=true` env var.

### What environment did it happen in?

Dev

**Comment by hasheddan** [comment]
@turkenh could you share the command you ran, as well as the output of `up --version`?

**Comment by turkenh** [comment]
@hasheddan it turned out to be something wrong with the command that I've used. So, this is a false alarm, sorry :)
