### ISSUE TITLE
Add `client-go` auth plugin

### ISSUE THREAD

**Issue by hasheddan** [upbound/up#258]
### What problem are you facing?

Currently, users can connect to control planes using `up ctp kubeconfig get`, which requires providing a token. Ideally, users could re-use the credential data that `up` already stores on disk in order to acquire credentials required to access a control plane.

### How could Upbound help solve your problem?

Add support for a [`client-go` auth plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) and update `up ctp kubeconfig get` to configure it (or introduce a new command).

**Comment by haarchri** [comment]
we close this issue - since this feature is for legacy SaaS - in Spaces SaaS we can use up ctx
