### ISSUE TITLE
`up ctp` commands that take a control plane name are listing `id` as the input

### ISSUE THREAD

**Issue by tnthornton** [upbound/up#263]
### What problem are you facing?
Now that we've introduced the new controlplane APIs, the older help text that was used for the deprecated APIs and while we were handling both versions now simply cause confusion.

### How could Upbound help solve your problem?
Update `ID` to `Name` in the controlplane commands. For example https://github.com/upbound/up/blob/main/cmd/up/controlplane/delete.go#L43.

**Comment by hasheddan** [comment]
Coming in a few moments :)

**Comment by hasheddan** [comment]
Fixed by https://github.com/upbound/up/pull/264
