### ISSUE TITLE
Manage Organization Users with the CLI

### ISSUE THREAD

**Issue by julienduchesne** [upbound/up#285]
### What problem are you facing?

I'd like to manage members of my organization with the CLI. The goal of this is to sync users from Github teams (our source of truth) to the org

Essentially, we could have a cron job that grabs the users from Github, deletes users that shouldn't be there and invite those that should.

### How could Upbound help solve your problem?

To achieve this, I'd need three commands:

- `up org users list` (shows both invites and actual users, as a field)
- `up org users create <user> <role>`
- `up org users delete <user>`

**Comment by jastang** [comment]
Just tagging this PR for the next release of `up` (v0.16.0) - timetable TBD.
