### ISSUE TITLE
M1 Processor Support

### ISSUE THREAD

**Issue by pieterv-icloud-com** [upbound/up#331]
### What happened?
Trying to install he up cli on a devcontainer running on a M1 Macbook Pro:

```
RUN curl -sL "https://cli.upbound.io" | sudo bash
```
and getting the following error

```
 > [dev_container_auto_added_stage_label 9/9] RUN curl -sL "https://cli.upbound.io" | sudo bash:
#0 1.105 Up does not support Linux / aarch64 at this time.
```

Expecting it to install inside the devcontainer.

Epic #

**Comment by alanraison** [comment]
The install script doesn't pick up the architecture correctly. Try running
```
curl -SL "https://cli.upbound.io" | sudo ARCH=arm64 bash
```
