### ISSUE TITLE
Add support for the `v1` version of `Provider.meta` for Upbound auth extension processing

### ISSUE THREAD

**Issue by ulucinar** [upbound/up#333]
### What problem are you facing?

While building an xpkg with the `up xpkg build` command, [we currently don't support](https://github.com/upbound/up/blob/7776c9db2c93d1f8dcce6ece05944dcf4a84ef2a/internal/xpkg/build.go#L196) the `v1` version of `Provider.meta`.

### How could Upbound help solve your problem?

We can extend the processing referenced above so that `Provider.meta@v1` is also supported for Upbound auth extensions while packaging providers using the `v1` version of the provider metadata API.

**Comment by haarchri** [comment]
this was done by https://github.com/upbound/up/commit/08d935564568044df3924fd0901ac4b148abf81b
