### ISSUE TITLE
Crossplaneproviders build with up v16 that don't specify spec.controller.image won't work

### ISSUE THREAD

**Issue by markussiebert** [upbound/up#334]
### What happened?

I created a new provider based on the [crossplane provider template]https://github.com/crossplane/provider-template. When I build and publish the provider without specifying an image in the provider crossplane.yaml, the resulting image won't work because I get the following error in the providerrevision that is created:

```
...
provider-abcd-673a879570d7" is invalid: spec.template.spec.containers[0].image: Required value
...
```

With version 0.13.0 of the up cli the build package works as expected and uses the package image as docker image for the provider. I had to add the following lines to the Makefile of the provider template to produce working crossplane provider packages:

```
UP_VERSION = v0.13.0
UP_CHANNEL = stable
UPTEST_VERSION = v0.5.0 
```

### How can we reproduce it?

Try to build a provider package without specifying the spec.controller.image field in the crossplane.yaml and install it.

### What environment did it happen in?

up cli v0.16.0 (latest cli) - the pinned version of the aws provider (0.13.0) works.

**Comment by markussiebert** [comment]
Just tried version 17 - works

**Comment by markussiebert** [comment]
Update further - interesting effects if you use to old up version with features of new crossplane :-)

**Comment by haarchri** [comment]
For that reason all package related features living now in crossplane cli
