### ISSUE TITLE
Login should be enough to get kubeconfig

### ISSUE THREAD

**Issue by sttts** [upbound/up#338]
### What problem are you facing?
 
```shell
$ up login
$ up cfg list
NAME                    ID                                     STATUS   DEPLOYED CONFIGURATION     CONFIGURATION STATUS
sttts-test              b5634552-731b-430f-bd9c-0753a0ec557a   ready    up-test-configuration      ready
$ up ctp kubeconfig get -a upbound sttts-test
up: error: missing flags: --token=STRING
```

This is unexpected that one needs a service account (API token).

### How could Upbound help solve your problem?

Epic #

**Comment by AlainRoy** [comment]
Just for reference, it is documented:
https://docs.upbound.io/cli/command-reference/#controlplane-kubeconfig-get
https://docs.upbound.io/concepts/managed-control-planes/#connect-directly-to-your-mcp

Stefan, do you have a proposal for an alternate approach? Do you think the token should be auto-generated? Another authentication method should be used/

**Comment by sttts** [comment]
`--generate-token` that calls the API to create a token.

**Comment by haarchri** [comment]
all possible now with up ctx
