### ISSUE TITLE
UXP install command does not work with the latest release

### ISSUE THREAD

**Issue by turkenh** [upbound/up#369]
### What happened?

Trying to install UXP following [the documentation](https://docs.upbound.io/uxp/install/#install-upbound-universal-crossplane) but getting the error below:

```
❯ up uxp install
up: error: uxp.Cmd.AfterApply(): couldn't find binding of type *upbound.Context for parameter 1 of func(*kong.Context, *upbound.Context) error(), use kong.Bind(*upbound.Context)
```

It works fine with `v0.18.0` but fails with `v0.19.0`.

### How can we reproduce it?

Try the following with release `v0.19.0`

```
up uxp install
```

### What environment did it happen in?

```
❯ up --version
v0.19.0
```

**Comment by branden** [comment]
Thanks @turkenh! This is fixed with v0.19.1.

```
branden@crateria up % up --version
v0.19.1
branden@crateria up % up uxp install
UXP 1.13.2-up.1 installed
branden@crateria up %
```
