### ISSUE TITLE
Support Spaces profiles in `up ctp` commands

### ISSUE THREAD

**Issue by branden** [upbound/up#374]
Support Spaces profiles introduced by #373 in `up ctp` commands. Affected commands and their changes are listed below.

### `configuration`, `provider`, `pull-secret`

These commands are not supported with Spaces. If the default profile is for Spaces, fail with an error.

### `create`, `delete`, `get`, `list`, `connect`, `kubeconfig`

If the default profile is for Saas, there's no change to behavior.

If the default profile is for Spaces, execute the equivalent operation on a `ControlPlane` resource on the Spaces cluster's apiserver. CRUD operations should translate directly. `connect` will need to deploy `mcp-connector` configured to connect to a control plane in the Space. `kubeconfig` will need to retrieve the control plane's kubeconfig from the Spaces apiserver.

**Comment by RedbackThomson** [comment]
Closed as the introduction of spaces into cloud has fundamentally changed `up` and this is no longer applicable. Profiles are no longer required for spaces in favour of using Kubeconfigs
