### ISSUE TITLE
On `up ctp create ctp1`: Internal Server Error

### ISSUE THREAD

**Issue by sttts** [upbound/up#402]
### What happened?

This might be a server error too. But creating a control plane from the command line seems to be broken.

### How can we reproduce it?

Log into your account with `up`. Then `up ctp create some-name`.

### What environment did it happen in?

Prod.

**Comment by sttts** [comment]
Double checked whether the configuration name flag `--configuration-name=caas` helps. It doesn't.

It a bug on its own that I don't get a message from the CLI before the server is even contacted that the configuration name is not passed. The doc says `The name of the Configuration. This property is required for cloud control planes.`.

**Comment by AlainRoy** [comment]
This definitely used to work. The fact that it's not working now is pointing to the need for more automated testing to catch these problems.

**Comment by RedbackThomson** [comment]
Closed as the introduction of spaces into cloud has fundamentally changed `up` and this is no longer applicable.
