### ISSUE TITLE
Update canned PR text

### ISSUE THREAD

**Issue by chrishalbert** [upbound/up#413]
### What happened?
While submitting and pull request, I tried to run `make reviewable` locally. It looks like this may have been removed at some point. Also, there is versioning information that I'm unfamiliar with; perhaps that could also be modified, or elaborated upon for clarity sake.

Epic #

### How can we reproduce it?
I left the canned PR checkboxes (unchecked) in https://github.com/upbound/up/pull/411

### What environment did it happen in?
N/A - github conf

**Comment by tnthornton** [comment]
Hi @chrishalbert ! The `reviewable` target should be coming from the `build` git submodule. When you set up the repo locally, were you able to get a local copy of the build submodule pulled?

**Comment by chrishalbert** [comment]
Sorry about that! I jumped to conclusions a little too quick.

**Comment by tnthornton** [comment]
No worries!
