### ISSUE TITLE
Edit deletion protection on existing group

### ISSUE THREAD

**Issue by branden** [upbound/up#475]
### What problem are you facing?

I can create a deletion-protected group with `up group create --deletion-protection`, but there's no option to add (or remove) deletion protection to an existing group.

### How could Upbound help solve your problem?

Add an `up group` subcommand that allows editing deletion protection for an existing group.

**Comment by RedbackThomson** [comment]
Deletion protection is not a feature that should be exposed to the user, it is a security setting configured by the controller. It can be shown in the group list, but should be removed altogether from create/update.
