### ISSUE TITLE
M1 Mac Instructions

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/up#58]
While `up` is a native M1 Mac executable available in [homebew](https://github.com/upbound/homebrew-tap), developers on M1 macs may wish to run UXP against a local Kind or Minikube cluster for testing. UXP already supports arm64 images so any arm64-compatible version of Kubernetes should run if Docker version > 3.3.1 is installed.

## Docker

Ensure that you are running a version of Docker that supports Apple Silicon: https://docs.docker.com/docker-for-mac/apple-silicon/ 

## Kind 

M1 Mac support (via arm64 node images)  in Kind is currently a [WIP](https://github.com/kubernetes-sigs/kind/pull/2176).

There is a workaround to build your own images: https://github.com/kubernetes-sigs/kind/issues/166#issuecomment-744417522

Until issue #2176 is closed, a custom image can be used as in the example below:

```shell
brew install kind
kind create cluster --image rossgeorgiev/kind-node-arm64:v1.21
up uxp install
```

## Minikube

Minikube currently supports M1 Macs out of the box:

```
brew install minikube
minikube start
up uxp install
```

**Comment by hasheddan** [comment]
@stevendborrelli I think these instructions might be more relevant for htttps://github.com/upbound/universal-crossplane since they primarily involve setting up a Kubernetes cluster for UXP to run in. All `up` components match the same workflow you would run on any other platform. What do you think?

**Comment by stevendborrelli** [comment]
I agree. I will add it to to UXP documentation.
