### ISSUE TITLE
`up ctx upbound/unreachable/default` wrong error message for unreachable space

### ISSUE THREAD

**Issue by sttts** [upbound/up#582]
### What happened?

When trying to connect to an unreachable space, the interactive mode shows it greyed out:

<img width="368" alt="Bildschirmfoto 2024-07-12 um 12 39 24" src="https://github.com/user-attachments/assets/58f65518-fd89-4141-a303-7d1b232194eb">

But when trying to connect non-interactively it shows:

```sh
up ctx upbound/unreachable/default
up: error: ctx.Cmd.Run(): "unreachable" not found in: upbound/
```

Epic #

**Comment by adamwg** [comment]
@sttts `up ctx upbound/unreachable/default` is looking for a space with the name `unreachable`, which doesn't exist. What do you see if you do `up ctx upbound/attached-8ggmk/default`?

**Comment by sttts** [comment]
I think "unreachable" above was just a placeholder to explain the problem. The controlplane was actually existing, just not reachable :) And I got the error written above.

**Comment by sttts** [comment]
When trying `up ctx upbound/attached-8ggmk/default` now, with a broken token I believe, I get this output which is also wrong:
```
$ up ctx upbound/attached-8ggmk/default
up: error: ctx.Cmd.Run(): "upbound" not found in:
```

**Comment by sttts** [comment]
And this is clearly not correct: it exists, is just unreachable:
```
$ up ctx
...
        [space] attached-8ggmk (unreachable)
```
