### ISSUE TITLE
Support population of kubeconfig files

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/up#86]
Currently it is a [ manual process ](https://cloud.upbound.io/docs/upbound-cloud/connecting-to-control-planes/#connect-to-control-plane) add cluster credentials of an Upbound-hosted cluster to a user's kubeconfig file.

Support the ability to populate a kubeconfig file from an Upbound Cloud hosted control plane, something like;

```shell
up cloud controlplane get kubeconfig
```

**Comment by hasheddan** [comment]
Very much in support of this, with the caveat that I would prefer `kubeconfig get` to terminate with a verb :)
https://github.com/upbound/up/blob/main/docs/commands.md#commands

**Comment by psinghal20** [comment]
Hi @hasheddan, I wanted to take a stab at this issue. I took a quick look at the codebase and had some questions regarding the API and the SDK.
- Currently, the SDK provides a method to fetch a control plane using its ID only. Is there any progress to fetch control plane details via name?
- To connect CLI with the cloud-hosted control plane, we require an access token. Now, `up` can either take this access token as input or create one for the user. We could add flags for both options, either supply an input token using `--token=<TOKEN>` or provide `--create` a flag and let `up` handle creation for you. Let me know what you think about this.
- Do you think there are any cons in relying on the `os/exec` package to run `kubectl` commands? If yes, do you have anything else in mind regarding this?

Also, what would be the right channel to ask questions regarding upbound-related development? Thanks! :smile:

**Comment by hasheddan** [comment]
@psinghal20 we can chat more on the [#upbound](https://crossplane.slack.com/archives/upbound) channel on Crossplane slack :)
