### ISSUE TITLE
Need a way to create self-hosted control planes without kube-uid

### ISSUE THREAD

**Issue by turkenh** [upbound/up#89]
### What problem are you facing?

In some scenarios, kube-cluster uid is not known or easily accessible by the user but available to agent running on the cluster. 

Deployments through marketplaces are a good example here. For example, while deploying through Rancher marketplace, all deployment flow can be completed through UI without connecting cluster from a local terminal (with up installed).

### How could up cli help solve your problem?

It should be possible to create a self-hosted control plane and obtain a **control plane token** without cluster connectivity or providing kube-uid to the cli.

Or to unify the experience, we can always leave setting kube-uid to the agent (with the first connection attempt) and `up cloud controlplane attach $NAME` command never sets kube-uid.

**Comment by hasheddan** [comment]
@turkenh thanks for opening this! I was not aware that the API accepted `Create` requests for self-hosted control-planes without the kube cluster ID, but knowing that, I would advocate for always having agent set it as you suggest.
